version: "3"
services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
      - 55679:55679
    volumes:
      - ./otel-collector-config.yaml:/conf/otel-collector-config.yaml
